package appSuperMercado.Interfaces;

import appSuperMercado.dao.ProductoDAO;
import appSuperMercado.modelo.Producto;
import dao.RegistrosVentas;
import dao.VentasPDF;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.DetallesVentas;
import modelo.EncabezadoFactura;
/**
 *
 * @author DELL
 */
public class Vender extends javax.swing.JFrame {

    /**
     * Creates new form Ventas
     */
    ArrayList<DetallesVentas> listaProductos = new ArrayList<>();
    private DetallesVentas producto;
    public Vender() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Ventas");
        this.setSize(1062,735);
    }

     ProductoDAO productoDao = new  ProductoDAO();   
     
     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableTotal = new javax.swing.JTable();
        btnAggProductoExistente = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        lblVendedor1 = new javax.swing.JLabel();
        lblVendedor2 = new javax.swing.JLabel();
        lblVendedor3 = new javax.swing.JLabel();
        lblVendedor5 = new javax.swing.JLabel();
        lblVendedor6 = new javax.swing.JLabel();
        lblVendedor7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblVendedor4 = new javax.swing.JLabel();
        btnCredito = new javax.swing.JButton();
        lblVendedor10 = new javax.swing.JLabel();
        lblVendedor12 = new javax.swing.JLabel();
        txtFnit = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        txtSubtotal = new javax.swing.JTextField();
        txtFnit2 = new javax.swing.JTextField();
        txtRecargoTotal = new javax.swing.JTextField();
        btnEfectivo = new javax.swing.JButton();
        btnDebito = new javax.swing.JButton();
        lblVendedor13 = new javax.swing.JLabel();
        lblVendedor14 = new javax.swing.JLabel();
        txtTOTAL = new javax.swing.JTextField();
        lblVendedor8 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblVendedor15 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        Atrás = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 131, 28));

        JTableTotal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Código de Barras", "Categoría", "Tipo de precio", "Precio", "Imágen"
            }
        ));
        JTableTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(JTableTotal);

        btnAggProductoExistente.setText("Vender Producto Existente");
        btnAggProductoExistente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggProductoExistenteActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Agregar Nuevo Producto");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("FINALIZAR COMPRA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblVendedor1.setBackground(new java.awt.Color(0, 0, 153));
        lblVendedor1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblVendedor1.setForeground(new java.awt.Color(255, 255, 255));
        lblVendedor1.setText("REPORTES:");

        lblVendedor2.setBackground(new java.awt.Color(0, 0, 153));
        lblVendedor2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblVendedor2.setForeground(new java.awt.Color(255, 255, 255));
        lblVendedor2.setText("Nombre Cliente: ");

        lblVendedor3.setBackground(new java.awt.Color(0, 0, 153));
        lblVendedor3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblVendedor3.setForeground(new java.awt.Color(255, 255, 255));
        lblVendedor3.setText("-REALIZA TU VENTA-");

        lblVendedor5.setBackground(new java.awt.Color(0, 0, 153));
        lblVendedor5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblVendedor5.setForeground(new java.awt.Color(255, 255, 255));
        lblVendedor5.setText("Recargo total: ");

        lblVendedor6.setBackground(new java.awt.Color(0, 0, 153));
        lblVendedor6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblVendedor6.setForeground(new java.awt.Color(255, 255, 255));
        lblVendedor6.setText("-DATOS GENERALES DE VENTA-");

        lblVendedor7.setBackground(new java.awt.Color(0, 0, 153));
        lblVendedor7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblVendedor7.setForeground(new java.awt.Color(255, 255, 255));

        jButton2.setText("REPORTE DEL DÍA .pdf");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("REPORTE DEL DÍA .xlxs");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblVendedor4.setBackground(new java.awt.Color(0, 0, 153));
        lblVendedor4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblVendedor4.setForeground(new java.awt.Color(255, 255, 255));
        lblVendedor4.setText("-MÉTODOS DE PAGO-");

        btnCredito.setText("Tarjeta de Credito");
        btnCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditoActionPerformed(evt);
            }
        });

        lblVendedor10.setBackground(new java.awt.Color(0, 0, 153));
        lblVendedor10.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblVendedor10.setForeground(new java.awt.Color(255, 255, 255));
        lblVendedor10.setText("Subtotal:");

        lblVendedor12.setBackground(new java.awt.Color(0, 0, 153));
        lblVendedor12.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblVendedor12.setForeground(new java.awt.Color(255, 255, 255));
        lblVendedor12.setText("NIT: ");

        txtFnit.setText("se ingresará");

        txtNombreCliente.setText("se obtendrá de la db e inicio de sesion");

        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });

        txtFnit2.setText("se obtendrá de la db e inicio de sesion");
        txtFnit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFnit2ActionPerformed(evt);
            }
        });

        txtRecargoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecargoTotalActionPerformed(evt);
            }
        });

        btnEfectivo.setText("En efectivo");
        btnEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfectivoActionPerformed(evt);
            }
        });

        btnDebito.setText("Tarjeta de Debto");
        btnDebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDebitoActionPerformed(evt);
            }
        });

        lblVendedor13.setBackground(new java.awt.Color(0, 0, 153));
        lblVendedor13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblVendedor13.setForeground(new java.awt.Color(255, 255, 255));
        lblVendedor13.setText("SUPER MERCADOS LA TORRE");

        lblVendedor14.setBackground(new java.awt.Color(0, 0, 153));
        lblVendedor14.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblVendedor14.setForeground(new java.awt.Color(255, 255, 255));
        lblVendedor14.setText("Total con impuestos: ");

        txtTOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTOTALActionPerformed(evt);
            }
        });

        lblVendedor8.setBackground(new java.awt.Color(0, 0, 153));
        lblVendedor8.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblVendedor8.setForeground(new java.awt.Color(255, 255, 255));
        lblVendedor8.setText("Nombre Vendedor: ");

        txtID.setText("se obtendrá de la db");
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        lblVendedor15.setBackground(new java.awt.Color(0, 0, 153));
        lblVendedor15.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblVendedor15.setForeground(new java.awt.Color(255, 255, 255));
        lblVendedor15.setText("ID Cliente: ");

        jButton4.setText("GENERAR FACTURA");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Atrás.setText("<-Atrás");
        Atrás.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrásActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVendedor2)
                                    .addComponent(lblVendedor12)
                                    .addComponent(lblVendedor15)
                                    .addComponent(lblVendedor10)
                                    .addComponent(lblVendedor5)
                                    .addComponent(lblVendedor8)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblVendedor14)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreCliente)
                                    .addComponent(txtFnit2)
                                    .addComponent(txtFnit)
                                    .addComponent(txtRecargoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSubtotal)))
                            .addComponent(jButton1)
                            .addComponent(lblVendedor1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4))
                            .addComponent(jButton3))
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVendedor3)
                        .addGap(149, 149, 149))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(lblVendedor7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(lblVendedor4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(lblVendedor6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Atrás)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnAggProductoExistente)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jToggleButton2))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnEfectivo)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnCredito)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnDebito))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblVendedor13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(lblVendedor3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Atrás)
                            .addComponent(lblVendedor13))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAggProductoExistente)
                            .addComponent(jToggleButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVendedor4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCredito)
                            .addComponent(btnDebito)
                            .addComponent(btnEfectivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVendedor6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVendedor8)
                            .addComponent(txtFnit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVendedor2)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVendedor12)
                            .addComponent(txtFnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVendedor15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVendedor10)
                            .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVendedor5)
                            .addComponent(txtRecargoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVendedor14)
                            .addComponent(txtTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(lblVendedor7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVendedor1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDebitoActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null,"¿Desea pagar con tarjeta de debito?");
        
        if(respuesta==JOptionPane.YES_OPTION){
             double totaRecargo = (subtotal+(subtotal*0.05));
            JOptionPane.showMessageDialog(null,"El total a pagar con un 5% de recargo es: "+(totaRecargo));
            txtTOTAL.setText(String.valueOf(totaRecargo));
        }else{
            JOptionPane.showMessageDialog(null, "Elija otro método de pago");
        }
    }//GEN-LAST:event_btnDebitoActionPerformed
    // EFECTIVO
    private void btnEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfectivoActionPerformed
        // TODO add your handling code here:        
        int respuesta = JOptionPane.showConfirmDialog(null,"¿Dese paga en efectivo?");
       
        if(respuesta == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(null,"El total a pagar es: "+(subtotal*0.12));
            txtSubtotal.setText(String.valueOf(subtotal));
            txtTOTAL.setText(String.valueOf(subtotal));
        }else{
            JOptionPane.showMessageDialog(null, "Elija otro método de pago");
        }
        
        
    }//GEN-LAST:event_btnEfectivoActionPerformed

    private void txtFnit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFnit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFnit2ActionPerformed

    private void btnCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditoActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(null,"¿Desea pagar con tarjeta de credito?");
        
        if(respuesta==JOptionPane.YES_OPTION){
            double recargo = subtotal*0.05;
            txtRecargoTotal.setText(String.valueOf(recargo));
            double totaRecargo = subtotal+(recargo);
            JOptionPane.showMessageDialog(null,"El total a pagar con un 5% de recargo es: "+(totaRecargo));
            txtTOTAL.setText(String.valueOf(totaRecargo));
        }else{
            JOptionPane.showMessageDialog(null, "Elija otro método de pago");
        }
    }//GEN-LAST:event_btnCreditoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Compra realizada con éxito");
        JOptionPane.showMessageDialog(null,"Ya podrá realizar reportes");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        AggProducto agregarPro = new AggProducto();
        agregarPro.setVisible(true);

    }//GEN-LAST:event_jToggleButton2ActionPerformed
    double subtotal =0;
    private void btnAggProductoExistenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggProductoExistenteActionPerformed
        //verificar si existe el producto segun su código
        String input = JOptionPane.showInputDialog(null,"Ingrese el código del producto: ");
          
        if(input !=null && !input.isEmpty()){
            try{
                int codigo = Integer.parseInt(input);
                Producto producto = productoDao.getProductoPorCodigo(codigo);
                if(producto !=null){
                    DefaultTableModel modeloTabla = (DefaultTableModel) JTableTotal.getModel();
                     // Crear una fila con los datos del producto
                Object[] fila = {
                    producto.getNombreProducto(), 
                    producto.getCodigo(), 
                    producto.getNombreCategoria(), 
                    producto.getPrecio()
                };
                 modeloTabla.addRow(fila);
                 subtotal+=producto.getPrecio();
                 
                 txtSubtotal.setText(String.valueOf(subtotal));
                }else{
                    JOptionPane.showMessageDialog(null, "Producto no encontrado.");
                }
            }catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Por favor, ingrese un código válido.");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese el codigo del producto");
        }
    }//GEN-LAST:event_btnAggProductoExistenteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        EncabezadoFactura cabeceraVenta = new EncabezadoFactura();
        DetallesVentas detalleVenta = new DetallesVentas();
        RegistrosVentas controlVenta = new RegistrosVentas();
        
             String fechaActual = "";
        Date date = new Date();
        fechaActual = new SimpleDateFormat("yyyy/MM/dd").format(date);

        if (txtNombreCliente !=null) {
           double total = Double.parseDouble(txtTOTAL.getText());

            if(total >= 1) {
                //metodo para obtener el id del cliente
                //registrar cabecera
                int id = Integer.parseInt(txtID.getText());
                cabeceraVenta.setIdCabeceraventa(0);
                cabeceraVenta.setIdCliente(id);
                cabeceraVenta.setValorPagar(Double.parseDouble(txtTOTAL.getText()));
                cabeceraVenta.setFechaVenta(fechaActual);
                cabeceraVenta.setEstado(1);

                if (controlVenta.guardar(cabeceraVenta)) {
                    JOptionPane.showMessageDialog(null, "¡Venta Registrada!");
                    
                    //Generar la factura de venta
                    VentasPDF pdf = new VentasPDF();
//                    pdf.DatosCliente(txtID);s
                    pdf.generarFacturaPDF();

                    //guardar detalle
                    for (DetallesVentas elemento : listaProductos) {
                        detalleVenta.setIdDetalleVenta(0);
                        detalleVenta.setIdCabeceraVenta(0);
                        detalleVenta.setIdProducto(elemento.getIdProducto());
                        detalleVenta.setCantidad(elemento.getCantidad());
                        detalleVenta.setPrecioUnitario(elemento.getPrecioUnitario());
                        detalleVenta.setSubTotal(elemento.getSubTotal());
                        detalleVenta.setDescuento(elemento.getDescuento());
                        detalleVenta.setIva(elemento.getIva());
                        detalleVenta.setTotalPagar(elemento.getTotalPagar());
                        detalleVenta.setEstado(1);

                        if (controlVenta.guardarDetalle(detalleVenta)) {
                            //System.out.println("Detalle de Venta Registrado");

                            txtSubtotal.setText("0.0");
//                            txt_iva.setText("0.0");
                            txtSubtotal.setText("0.0");
                            txtTOTAL.setText("0.0");
                            txtTOTAL.setText("");
//                            txt_cambio.setText("0.0");
//                            auxIdDetalle = 1;

//                            this.CargarComboClientes();
//                            this.RestarStockProductos(elemento.getIdProducto(), elemento.getCantidad());

                        } else {
                            JOptionPane.showMessageDialog(null, "¡Error al guardar detalle de venta!");
                        }
                    }
                    //vaciamos la lista
                    listaProductos.clear();
                    listaTablaProductos();

                } else {
                    JOptionPane.showMessageDialog(null, "¡Error al guardar cabecera de venta!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "¡Seleccione un producto!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "¡Seleccione un cliente!");
        }
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void AtrásActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrásActionPerformed
        // TODO add your handling code here:
        Vendedor vendedor = new Vendedor();
        this.setVisible(false);
        vendedor.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AtrásActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtTOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTOTALActionPerformed
        // TODO add your handling code here:
            double subtotal =0;
    }//GEN-LAST:event_txtTOTALActionPerformed

    private void txtRecargoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecargoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecargoTotalActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atrás;
    public static javax.swing.JTable JTableTotal;
    private javax.swing.JToggleButton btnAggProductoExistente;
    private javax.swing.JButton btnCredito;
    private javax.swing.JButton btnDebito;
    private javax.swing.JButton btnEfectivo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lblVendedor1;
    private javax.swing.JLabel lblVendedor10;
    private javax.swing.JLabel lblVendedor12;
    private javax.swing.JLabel lblVendedor13;
    private javax.swing.JLabel lblVendedor14;
    private javax.swing.JLabel lblVendedor15;
    private javax.swing.JLabel lblVendedor2;
    private javax.swing.JLabel lblVendedor3;
    private javax.swing.JLabel lblVendedor4;
    private javax.swing.JLabel lblVendedor5;
    private javax.swing.JLabel lblVendedor6;
    private javax.swing.JLabel lblVendedor7;
    private javax.swing.JLabel lblVendedor8;
    private javax.swing.JTextField txtFnit;
    private javax.swing.JTextField txtFnit2;
    public javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtRecargoTotal;
    private javax.swing.JTextField txtSubtotal;
    public static javax.swing.JTextField txtTOTAL;
    // End of variables declaration//GEN-END:variables

    private void listaTablaProductos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
